export const MESSAGE_CODES = {
    TOKEN_EXPIRED: 3,
    FORM_INPUT_INVALID: 7,
    ITEM_NOT_FOUND: 9,
    OK: 200,
    CLIENT_ERROR: 1000,
    CLIENT_NAVIGATE_ERROR: 1001,
    CLIENT_NO_PERMISSION: 1002,
};
